language: java
jdk: openjdk13

os:
  - linux
  - osx

env:
  - matrix:
    - TARGET : "lab1"
    - TARGET : "lab2"
    - TARGET : "lab3"
    - TARGET : "lab4"
    - TARGET : "lab5"

script:
  - cd $TARGET && mvn clean package
