language: java

matrix:
  include:
    - name: "Test Linux"
      jdk: openjdk13
    - name: "Test macOS"
      jdk: openjdk13
      os: osx
    - name: "Test Windows"
      jdk: openjdk13
      os: windows

script:
  - cd lab1
  - mvn clean package
